# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1df8f87d08fb1934591809d4dba52af78b3b6af0a2b5bef4b1919d7b1aca370af8991ea834d50fa807640034dada0ba6c978df79b11d33c1b6a4ea011b913e8

test:
  secret_key_base: 8ee17b2c2f94b4f44b5b50f0167edeaf2a2215fe2a3fee34e143b5baa6572551421d265d825c3f0189e888a5f486dae2981896dd0acb7fe97b728dfb3a817d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
